package Boundary.Vecchio;

import Boundary.FormHome;
import Boundary.FormOrdinazione;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class Contenitore {
    private JPanel contentPane;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }



    public static void main(String[] args) {

        JFrame frame = new JFrame("App");
        JPanel mainPanel = new JPanel();
        CardLayout cl= new CardLayout();
        mainPanel.setLayout(cl);

        FormHome accesso= new FormHome();
        FormOrdinazione ord= new FormOrdinazione();

        mainPanel.add(accesso.$$$getRootComponent$$$(),"ACCESSO");
        mainPanel.add(ord.$$$getRootComponent$$$(),"ORDINA");

        frame.setContentPane(mainPanel);
        frame.setSize(500,400);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        cl.show(mainPanel,"ACCESSO");
    }
}

