package Boundary;

import Controller.GestisciOrdineController;
import Entity.Ordine;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class FormGestisciOrdine {
    private JPanel contentPane;
    private JComboBox cmbListaOrdini;
    private JButton VISUALIZZAButton;
    private JButton INDIETROButton;
    private Navigator navigator;

    //metodo per il pulsante visualizza
    private void visualizzaDettagliOrdine() {
        Ordine ordineScelto = (Ordine) cmbListaOrdini.getSelectedItem();

        //il controllo viene fatto direttamente nella boundary
        if (ordineScelto == null) {
            JOptionPane.showMessageDialog(null, " selezionare un ordine dalla lista!! ");
            return;
        }

        //apre il primo POP-UP
        FormDettagliOrdine dettagli = new FormDettagliOrdine(ordineScelto);
        Window finestraPadre = SwingUtilities.getWindowAncestor(contentPane);
        JDialog dialogDettagli = new JDialog((Frame) finestraPadre, "Dettagli Ordine", true);
        dialogDettagli.setContentPane(dettagli.getContentPane());
        dialogDettagli.pack();
        dialogDettagli.setLocationRelativeTo(finestraPadre);
        dialogDettagli.setVisible(true);

        //appena il pop-up viene chiuso aggiorna gli ordini
        SelezionaOrdine();
    }

    //blocco generato automaticamente dopo aver fatto actionListener
    public FormGestisciOrdine(Navigator navigator) {
        this.navigator = navigator;

        //metodo che mi permette di collegare il controller
        SelezionaOrdine();

        VISUALIZZAButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                visualizzaDettagliOrdine();
            }
        });

        INDIETROButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                navigator.showGestioneRistorante();
            }
        });

    }

    private void SelezionaOrdine() {
        cmbListaOrdini.removeAllItems();
        List<Ordine> ordini = GestisciOrdineController.getOrdiniInviati();
        for (Ordine o : ordini) {
            cmbListaOrdini.addItem(o);
        }
    }

    //metodo per restituire il ContentPane e rispettare il private
    public JPanel getContentPane() {
        return contentPane;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.setEnabled(true);
        contentPane.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("LISTA ORDINI");
        contentPane.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("SELEZIONARE L'ORDINE TRA QUELLI IN LISTA");
        contentPane.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cmbListaOrdini = new JComboBox();
        contentPane.add(cmbListaOrdini, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        VISUALIZZAButton = new JButton();
        VISUALIZZAButton.setText("VISUALIZZA");
        contentPane.add(VISUALIZZAButton, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        INDIETROButton = new JButton();
        INDIETROButton.setText("INDIETRO");
        contentPane.add(INDIETROButton, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}