//QUESTO FORM SERVE PER IL "BUTTON ACCETTA" DEL FORM DETTAGLIORDINE

package Boundary;

import Entity.Ordine;
import Controller.GestisciOrdineController;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FormAggiornaStatoOrdine {

    private JLabel lblIdOrdine;
    private JButton AGGIORNAINCONSEGNAButton;
    private JButton HOMEButton;
    private JLabel lblStatoAttuale;
    private JPanel contentPane;


    public FormAggiornaStatoOrdine(Ordine ordine) {

        if (ordine != null) {
            lblIdOrdine.setText(String.valueOf(ordine.getId()));
            lblStatoAttuale.setText(ordine.getStatoOrdine());
        }

        //richiama il metodo segnalaOrdinePronto del controller
        AGGIORNAINCONSEGNAButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean successo = GestisciOrdineController.segnalaOrdinePronto(ordine);

                if (successo) {
                    JOptionPane.showMessageDialog(contentPane, "L'ordine è ora in consegna");
                    lblStatoAttuale.setText(ordine.getStatoOrdine());

                    //forziamo l'aggiornamento dell'ordine in ram
                    lblStatoAttuale.setText("In consegna");

                    //disabilitiamo cosi da evitare doppio click
                    AGGIORNAINCONSEGNAButton.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(contentPane, "Errore durante l'aggiornamento dello stato");
                }
            }
        });

        HOMEButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Chiude anche quest'ultimo pop-up e ritorniamo alla lista
                Window popUpAttuale = SwingUtilities.getWindowAncestor(contentPane);
                if(popUpAttuale != null) popUpAttuale.dispose();
            }
        });
    }

    //metodo per restituire il ContentPane e rispettare il private
    public JPanel getContentPane() {
        return contentPane;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("AGGIORNAMENTI STATO ORDINE");
        contentPane.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("ID ORDINE: ");
        contentPane.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblIdOrdine = new JLabel();
        lblIdOrdine.setText("Label");
        contentPane.add(lblIdOrdine, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        AGGIORNAINCONSEGNAButton = new JButton();
        AGGIORNAINCONSEGNAButton.setHideActionText(true);
        AGGIORNAINCONSEGNAButton.setText("AGGIORNA IN CONSEGNA");
        contentPane.add(AGGIORNAINCONSEGNAButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        HOMEButton = new JButton();
        HOMEButton.setText("HOME");
        contentPane.add(HOMEButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("STATO ATTUALE:");
        contentPane.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblStatoAttuale = new JLabel();
        lblStatoAttuale.setText("Label");
        contentPane.add(lblStatoAttuale, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        contentPane.add(separator1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JSeparator separator2 = new JSeparator();
        contentPane.add(separator2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
