//QUESTO FORM SERVE PER IL "BUTTON VISUALIZZA" DEL FORM GESTISCIORDINE

package Boundary;

import Controller.GestisciOrdineController;
import Entity.Ordine;
import Entity.RigaCarrelloVirtuale;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FormDettagliOrdine {

    private JPanel contentPane;
    private JLabel lblIdOrdine;
    private JLabel lblStatoOrdine;
    private JLabel lblIndirizzo;
    private JTable tblPiatti;
    private JButton ACCETTAButton;
    private JButton RIFIUTAButton;

    public FormDettagliOrdine(Ordine ordineScelto) {

        if (ordineScelto != null) {
            lblIdOrdine.setText(String.valueOf(ordineScelto.getId()));
            lblStatoOrdine.setText(ordineScelto.getStatoOrdine());
            lblIndirizzo.setText(ordineScelto.getIndirizzoConsegna().getVia() + "" + ordineScelto.getIndirizzoConsegna().getCivico());

            String[] colonne = {"Nome Piatto", "Descrizione", "Prezzo Unitario", "Quantità"};

            //Creiamo il modello della tabella e blocchiamo la modifica delle celle da parte dell'utente
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(colonne, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Il ristoratore può solo leggere, non scrivere!
                }
            };

            //Estraiamo i dati dal carrello
            if (ordineScelto.getCarrello() != null) {
                for (RigaCarrelloVirtuale riga : ordineScelto.getCarrello()) {
                    // Costruiamo una riga con i 4 attributi presi da Piatto e RigaCarrello
                    Object[] rigaDati = {
                            riga.getPiatto().getNomePiatto(),
                            riga.getPiatto().getDescrizione(),
                            riga.getPiatto().getPrezzo() + " €",
                            riga.getQuantita()
                    };
                    model.addRow(rigaDati); // Aggiungiamo la riga al modello
                }
            }

            tblPiatti.setModel(model);
        }

        //qui si richiama il metodo accettaOrdine() del controller
        ACCETTAButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean successo = GestisciOrdineController.accettaOrdine(ordineScelto);

                if(successo) {
                    JOptionPane.showMessageDialog(contentPane, "Ordine ACCETTATO!!");

                    //chiudo questo pop-up e apro il pop-up successivo (FormAggiornaStatoOrdine)
                    Window popUpAttuale = SwingUtilities.getWindowAncestor(contentPane);
                    if(popUpAttuale != null) {
                        popUpAttuale.dispose();
                    }

                    FormAggiornaStatoOrdine aggiorna = new FormAggiornaStatoOrdine(ordineScelto);
                    JDialog dialogAggiorna = new JDialog((Frame) null, "Aggiorna Stato Ordine", true);
                    dialogAggiorna.setContentPane(aggiorna.getContentPane());
                    dialogAggiorna.pack();
                    dialogAggiorna.setLocationRelativeTo(null);
                    dialogAggiorna.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(contentPane, "Impossibile accettare l'ordine");
                }
            }
        });

        RIFIUTAButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean successo = GestisciOrdineController.rifiutaOrdine(ordineScelto);

                if(successo) {
                    JOptionPane.showMessageDialog(contentPane, "Ordine RIFIUTATO!!");

                    //si limita a chiudere il pop-up
                    Window popUpAttuale = SwingUtilities.getWindowAncestor(contentPane);
                    if(popUpAttuale != null) {
                        popUpAttuale.dispose();
                    }

                }
            }
        });
    }

    //metodo per restituire il ContentPane e rispettare il private
    public JPanel getContentPane() {
        return contentPane;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(8, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("DETTAGLI ORDINE SELEZIONATO:");
        contentPane.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("ID ORDINE:");
        contentPane.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblIdOrdine = new JLabel();
        lblIdOrdine.setText("Label");
        contentPane.add(lblIdOrdine, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("STATO ORDINE: ");
        contentPane.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblStatoOrdine = new JLabel();
        lblStatoOrdine.setText("Label");
        contentPane.add(lblStatoOrdine, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("INDIRIZZO CONSEGNA:");
        contentPane.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblIndirizzo = new JLabel();
        lblIndirizzo.setText("Label");
        contentPane.add(lblIndirizzo, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("PIATTI ORDINATI: ");
        contentPane.add(label5, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tblPiatti = new JTable();
        contentPane.add(tblPiatti, new GridConstraints(4, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        contentPane.add(separator1, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ACCETTAButton = new JButton();
        ACCETTAButton.setText("ACCETTA");
        contentPane.add(ACCETTAButton, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, -1), null, null, 0, false));
        RIFIUTAButton = new JButton();
        RIFIUTAButton.setText("RIFIUTA");
        contentPane.add(RIFIUTAButton, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator2 = new JSeparator();
        contentPane.add(separator2, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }




    /*public void main(String[] args) {
        FormDettagliOrdine dettagli = new FormDettagliOrdine(ordineScelto);
        JFrame nuovoFrame = new JFrame();
        nuovoFrame.setTitle("Dettagli Ordine");
        nuovoFrame.setContentPane(dettagli.contentPane);
        nuovoFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        nuovoFrame.pack();
        nuovoFrame.setLocationRelativeTo(null);
        nuovoFrame.setVisible(true);
    }
     */
}

